version: '3.8'

services:
  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6379:6379"

  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6380:6379"

  redis-3:
    image: redis:latest
    container_name: redis-3
    ports:
      - "6381:6379"
